// Data-fetching + row-mapping for the health report generator.
// Mirrors the shapes lib/trackingService.ts maps for the client, but only
// the fields insightsEngine.ts actually needs (no photo/full-nutrition mapping).
import type { SupabaseClient } from "@supabase/server/peer/supabase-js";
import type { BowelEntry, FoodEntry, WaterEntry } from "../../../types/tracking.ts";

type EntryRange = { startISO: string; endISO: string };

export async function fetchFoodEntries(
  supabase: SupabaseClient,
  range: EntryRange,
): Promise<Pick<FoodEntry, "id" | "timestamp" | "totalCalories" | "totalProtein" | "totalCarbs" | "totalFat" | "ingredients">[]> {
  const { data, error } = await supabase
    .from("food_entries")
    .select("id, timestamp, total_calories, total_protein, total_carbs, total_fat, food_ingredients(name)")
    .gte("timestamp", range.startISO)
    .lte("timestamp", range.endISO)
    .order("timestamp", { ascending: true });

  if (error) throw new Error(`fetchFoodEntries failed: ${error.message}`);

  return (data ?? []).map((row: any) => ({
    id: row.id,
    timestamp: row.timestamp,
    totalCalories: row.total_calories ?? undefined,
    totalProtein: row.total_protein ?? undefined,
    totalCarbs: row.total_carbs ?? undefined,
    totalFat: row.total_fat ?? undefined,
    ingredients: (row.food_ingredients ?? []).map((ing: any) => ({
      id: "",
      name: ing.name,
      amount: 0,
      unit: "g" as const,
    })),
  }));
}

export async function fetchWaterEntries(
  supabase: SupabaseClient,
  range: EntryRange,
): Promise<Pick<WaterEntry, "id" | "timestamp" | "totalVolume" | "volumeMl" | "ingredients">[]> {
  const { data, error } = await supabase
    .from("water_entries")
    .select("id, timestamp, total_volume, volume_ml, water_ingredients(name)")
    .gte("timestamp", range.startISO)
    .lte("timestamp", range.endISO)
    .order("timestamp", { ascending: true });

  if (error) throw new Error(`fetchWaterEntries failed: ${error.message}`);

  return (data ?? []).map((row: any) => ({
    id: row.id,
    timestamp: row.timestamp,
    totalVolume: row.total_volume ?? undefined,
    volumeMl: row.volume_ml,
    ingredients: (row.water_ingredients ?? []).map((ing: any) => ({
      id: "",
      name: ing.name,
      amount: 0,
      unit: "g" as const,
    })),
  }));
}

export async function fetchBowelEntries(
  supabase: SupabaseClient,
  range: EntryRange,
): Promise<BowelEntry[]> {
  const { data, error } = await supabase
    .from("bowel_entries")
    .select("id, timestamp, false_alarm, bristol_type, urgency, has_blood, pain_level, notes")
    .gte("timestamp", range.startISO)
    .lte("timestamp", range.endISO)
    .order("timestamp", { ascending: true });

  if (error) throw new Error(`fetchBowelEntries failed: ${error.message}`);

  return (data ?? []).map((row: any) => ({
    id: row.id,
    timestamp: row.timestamp,
    falseAlarm: row.false_alarm,
    bristolType: row.bristol_type ?? undefined,
    urgency: row.urgency,
    hasBlood: row.has_blood,
    painLevel: row.pain_level,
    notes: row.notes ?? undefined,
  }));
}

/** Rate limit: counts health_reports rows generated by the caller within the last `windowHours`. */
export async function countRecentReports(
  supabase: SupabaseClient,
  userId: string,
  windowHours: number,
): Promise<number> {
  const windowStartISO = new Date(Date.now() - windowHours * 60 * 60 * 1000).toISOString();

  const { count, error } = await supabase
    .from("health_reports")
    .select("id", { count: "exact", head: true })
    .eq("user_id", userId)
    .gte("generated_at", windowStartISO);

  if (error) throw new Error(`countRecentReports failed: ${error.message}`);
  return count ?? 0;
}
